package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotBaseWord;
import com.bot.game.dao.entity.BotBaseWordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BotBaseWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    int countByExample(BotBaseWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    int deleteByExample(BotBaseWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    int insert(BotBaseWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    int insertSelective(BotBaseWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    List<BotBaseWord> selectByExample(BotBaseWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    BotBaseWord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotBaseWord record, @Param("example") BotBaseWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotBaseWord record, @Param("example") BotBaseWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotBaseWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotBaseWord record);
}