package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotActivityUser;
import com.bot.game.dao.entity.BotActivityUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BotActivityUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity_user
     *
     * @mbggenerated
     */
    int countByExample(BotActivityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity_user
     *
     * @mbggenerated
     */
    int deleteByExample(BotActivityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity_user
     *
     * @mbggenerated
     */
    int insert(BotActivityUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity_user
     *
     * @mbggenerated
     */
    int insertSelective(BotActivityUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity_user
     *
     * @mbggenerated
     */
    List<BotActivityUser> selectByExample(BotActivityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotActivityUser record, @Param("example") BotActivityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotActivityUser record, @Param("example") BotActivityUserExample example);
}