package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotActivity;
import com.bot.game.dao.entity.BotActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BotActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    int countByExample(BotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    int deleteByExample(BotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    int insert(BotActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    int insertSelective(BotActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    List<BotActivity> selectByExample(BotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    BotActivity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotActivity record, @Param("example") BotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotActivity record, @Param("example") BotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotActivity record);
}