package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotBaseQian;
import com.bot.game.dao.entity.BotBaseQianExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotBaseQianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    int countByExample(BotBaseQianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    int deleteByExample(BotBaseQianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    int insert(BotBaseQian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    int insertSelective(BotBaseQian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    List<BotBaseQian> selectByExample(BotBaseQianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    BotBaseQian selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotBaseQian record, @Param("example") BotBaseQianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotBaseQian record, @Param("example") BotBaseQianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotBaseQian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_qian
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotBaseQian record);
}