package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotBottleMessage;
import com.bot.game.dao.entity.BotBottleMessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotBottleMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    int countByExample(BotBottleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    int deleteByExample(BotBottleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    int insert(BotBottleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    int insertSelective(BotBottleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    List<BotBottleMessage> selectByExample(BotBottleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    BotBottleMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotBottleMessage record, @Param("example") BotBottleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotBottleMessage record, @Param("example") BotBottleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotBottleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotBottleMessage record);
}