package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotDrinkRecord;
import com.bot.game.dao.entity.BotDrinkRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotDrinkRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    int countByExample(BotDrinkRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    int deleteByExample(BotDrinkRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    int insert(BotDrinkRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    int insertSelective(BotDrinkRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    List<BotDrinkRecord> selectByExample(BotDrinkRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    BotDrinkRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotDrinkRecord record, @Param("example") BotDrinkRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotDrinkRecord record, @Param("example") BotDrinkRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotDrinkRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotDrinkRecord record);
}