package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotEmoji;
import com.bot.game.dao.entity.BotEmojiExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotEmojiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    int countByExample(BotEmojiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    int deleteByExample(BotEmojiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    int insert(BotEmoji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    int insertSelective(BotEmoji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    List<BotEmoji> selectByExample(BotEmojiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    BotEmoji selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotEmoji record, @Param("example") BotEmojiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotEmoji record, @Param("example") BotEmojiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotEmoji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_emoji
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotEmoji record);
}