package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotGameRoomPlayer;
import com.bot.game.dao.entity.BotGameRoomPlayerExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotGameRoomPlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    int countByExample(BotGameRoomPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    int deleteByExample(BotGameRoomPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    int insert(BotGameRoomPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    int insertSelective(BotGameRoomPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    List<BotGameRoomPlayer> selectByExample(BotGameRoomPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    BotGameRoomPlayer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotGameRoomPlayer record, @Param("example") BotGameRoomPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotGameRoomPlayer record, @Param("example") BotGameRoomPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotGameRoomPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room_player
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotGameRoomPlayer record);

    // ========== 自定义方法 ==========

    /**
     * 根据userId查询用户当前所在房间
     */
    BotGameRoomPlayer selectByUserId(String userId);

    /**
     * 统计房间内人数
     */
    int countByRoomId(Long roomId);

    /**
     * 查询房间内所有玩家
     */
    List<BotGameRoomPlayer> selectByRoomId(Long roomId);

    /**
     * 根据房间ID和用户ID删除
     */
    int deleteByRoomIdAndUserId(@Param("roomId") Long roomId, @Param("userId") String userId);
}