package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotGameRoom;
import com.bot.game.dao.entity.BotGameRoomExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotGameRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    int countByExample(BotGameRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    int deleteByExample(BotGameRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    int insert(BotGameRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    int insertSelective(BotGameRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    List<BotGameRoom> selectByExample(BotGameRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    BotGameRoom selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotGameRoom record, @Param("example") BotGameRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotGameRoom record, @Param("example") BotGameRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotGameRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_room
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotGameRoom record);

    // ========== 自定义方法 ==========

    /**
     * 查询公开且等待中的房间
     */
    List<BotGameRoom> selectPublicWaitingRooms();

    /**
     * 根据房间号查询
     */
    BotGameRoom selectByRoomCode(String roomCode);

    /**
     * 检查房间号是否存在
     */
    boolean existsByRoomCode(String roomCode);

    /**
     * 查询超时的等待中房间
     */
    List<BotGameRoom> selectTimeoutWaitingRooms();
}