package com.bot.game.dao.mapper;

import java.util.List;

import com.bot.game.dao.entity.BotNotice;
import com.bot.game.dao.entity.BotNoticeExample;
import org.apache.ibatis.annotations.Param;

public interface BotNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    int countByExample(BotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    int deleteByExample(BotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    int insert(BotNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    int insertSelective(BotNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    List<BotNotice> selectByExample(BotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    BotNotice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotNotice record, @Param("example") BotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotNotice record, @Param("example") BotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotNotice record);
}