package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotRedPacket;
import com.bot.game.dao.entity.BotRedPacketExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotRedPacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    int countByExample(BotRedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    int deleteByExample(BotRedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    int insert(BotRedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    int insertSelective(BotRedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    List<BotRedPacket> selectByExample(BotRedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    BotRedPacket selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotRedPacket record, @Param("example") BotRedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotRedPacket record, @Param("example") BotRedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotRedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotRedPacket record);
}