package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotUserBox;
import com.bot.game.dao.entity.BotUserBoxExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotUserBoxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    int countByExample(BotUserBoxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    int deleteByExample(BotUserBoxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    int insert(BotUserBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    int insertSelective(BotUserBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    List<BotUserBox> selectByExample(BotUserBoxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    BotUserBox selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotUserBox record, @Param("example") BotUserBoxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotUserBox record, @Param("example") BotUserBoxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotUserBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_box
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotUserBox record);
}