package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotUserConfig;
import com.bot.game.dao.entity.BotUserConfigExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotUserConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    int countByExample(BotUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    int deleteByExample(BotUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    int insert(BotUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    int insertSelective(BotUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    List<BotUserConfig> selectByExample(BotUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    BotUserConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotUserConfig record, @Param("example") BotUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotUserConfig record, @Param("example") BotUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotUserConfig record);
}
