package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotUserSign;
import com.bot.game.dao.entity.BotUserSignExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotUserSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    int countByExample(BotUserSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    int deleteByExample(BotUserSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    int insert(BotUserSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    int insertSelective(BotUserSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    List<BotUserSign> selectByExample(BotUserSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    BotUserSign selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotUserSign record, @Param("example") BotUserSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotUserSign record, @Param("example") BotUserSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotUserSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_sign
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotUserSign record);
}