package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotUserAward;
import com.bot.game.dao.entity.BotUserAwardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BotUserAwardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    int countByExample(BotUserAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    int deleteByExample(BotUserAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    int insert(BotUserAward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    int insertSelective(BotUserAward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    List<BotUserAward> selectByExample(BotUserAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    BotUserAward selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotUserAward record, @Param("example") BotUserAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotUserAward record, @Param("example") BotUserAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotUserAward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_award
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotUserAward record);
}