package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotUser;
import com.bot.game.dao.entity.BotUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BotUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    int countByExample(BotUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    int deleteByExample(BotUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    int insert(BotUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    int insertSelective(BotUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    List<BotUser> selectByExample(BotUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    BotUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotUser record, @Param("example") BotUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotUser record, @Param("example") BotUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotUser record);
}