package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotUserBlindBox;
import com.bot.game.dao.entity.BotUserBlindBoxExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotUserBlindBoxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    int countByExample(BotUserBlindBoxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    int deleteByExample(BotUserBlindBoxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    int insert(BotUserBlindBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    int insertSelective(BotUserBlindBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    List<BotUserBlindBox> selectByExample(BotUserBlindBoxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    BotUserBlindBox selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotUserBlindBox record, @Param("example") BotUserBlindBoxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotUserBlindBox record, @Param("example") BotUserBlindBoxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotUserBlindBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotUserBlindBox record);
}