package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.BotUserWord;
import com.bot.game.dao.entity.BotUserWordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BotUserWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    int countByExample(BotUserWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    int deleteByExample(BotUserWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    int insert(BotUserWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    int insertSelective(BotUserWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    List<BotUserWord> selectByExample(BotUserWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    BotUserWord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BotUserWord record, @Param("example") BotUserWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BotUserWord record, @Param("example") BotUserWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BotUserWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BotUserWord record);
}