package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.JXCache;
import com.bot.game.dao.entity.JXCacheExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JXCacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    int countByExample(JXCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    int deleteByExample(JXCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    int insert(JXCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    int insertSelective(JXCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    List<JXCache> selectByExample(JXCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JXCache record, @Param("example") JXCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JXCache record, @Param("example") JXCacheExample example);
}