package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.JXShowHistoryQuery;
import com.bot.game.dao.entity.JXShowHistoryQueryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JXShowHistoryQueryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    int countByExample(JXShowHistoryQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    int deleteByExample(JXShowHistoryQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    int insert(JXShowHistoryQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    int insertSelective(JXShowHistoryQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    List<JXShowHistoryQuery> selectByExample(JXShowHistoryQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    JXShowHistoryQuery selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JXShowHistoryQuery record, @Param("example") JXShowHistoryQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JXShowHistoryQuery record, @Param("example") JXShowHistoryQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JXShowHistoryQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JXShowHistoryQuery record);
}