package com.bot.game.dao.mapper;

import com.bot.game.dao.entity.UserBind;
import com.bot.game.dao.entity.UserBindExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserBindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    int countByExample(UserBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    int deleteByExample(UserBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    int insert(UserBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    int insertSelective(UserBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    List<UserBind> selectByExample(UserBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    UserBind selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserBind record, @Param("example") UserBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserBind record, @Param("example") UserBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBind record);
}