package com.bot.game.dao.entity;

import java.io.Serializable;

public class BotBaseWord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.word
     *
     * @mbggenerated
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.probability
     *
     * @mbggenerated
     */
    private String probability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.begin_date
     *
     * @mbggenerated
     */
    private String beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.merit
     *
     * @mbggenerated
     */
    private Integer merit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.group_flag
     *
     * @mbggenerated
     */
    private String groupFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.rarity
     *
     * @mbggenerated
     */
    private String rarity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.prompt
     *
     * @mbggenerated
     */
    private String prompt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_base_word.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.id
     *
     * @return the value of bot_base_word.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.id
     *
     * @param id the value for bot_base_word.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.word
     *
     * @return the value of bot_base_word.word
     *
     * @mbggenerated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.word
     *
     * @param word the value for bot_base_word.word
     *
     * @mbggenerated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.memo
     *
     * @return the value of bot_base_word.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.memo
     *
     * @param memo the value for bot_base_word.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.probability
     *
     * @return the value of bot_base_word.probability
     *
     * @mbggenerated
     */
    public String getProbability() {
        return probability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.probability
     *
     * @param probability the value for bot_base_word.probability
     *
     * @mbggenerated
     */
    public void setProbability(String probability) {
        this.probability = probability == null ? null : probability.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.begin_date
     *
     * @return the value of bot_base_word.begin_date
     *
     * @mbggenerated
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.begin_date
     *
     * @param beginDate the value for bot_base_word.begin_date
     *
     * @mbggenerated
     */
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate == null ? null : beginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.end_date
     *
     * @return the value of bot_base_word.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.end_date
     *
     * @param endDate the value for bot_base_word.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.merit
     *
     * @return the value of bot_base_word.merit
     *
     * @mbggenerated
     */
    public Integer getMerit() {
        return merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.merit
     *
     * @param merit the value for bot_base_word.merit
     *
     * @mbggenerated
     */
    public void setMerit(Integer merit) {
        this.merit = merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.group_flag
     *
     * @return the value of bot_base_word.group_flag
     *
     * @mbggenerated
     */
    public String getGroupFlag() {
        return groupFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.group_flag
     *
     * @param groupFlag the value for bot_base_word.group_flag
     *
     * @mbggenerated
     */
    public void setGroupFlag(String groupFlag) {
        this.groupFlag = groupFlag == null ? null : groupFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.rarity
     *
     * @return the value of bot_base_word.rarity
     *
     * @mbggenerated
     */
    public String getRarity() {
        return rarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.rarity
     *
     * @param rarity the value for bot_base_word.rarity
     *
     * @mbggenerated
     */
    public void setRarity(String rarity) {
        this.rarity = rarity == null ? null : rarity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.prompt
     *
     * @return the value of bot_base_word.prompt
     *
     * @mbggenerated
     */
    public String getPrompt() {
        return prompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.prompt
     *
     * @param prompt the value for bot_base_word.prompt
     *
     * @mbggenerated
     */
    public void setPrompt(String prompt) {
        this.prompt = prompt == null ? null : prompt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_base_word.type
     *
     * @return the value of bot_base_word.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_base_word.type
     *
     * @param type the value for bot_base_word.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotBaseWord other = (BotBaseWord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWord() == null ? other.getWord() == null : this.getWord().equals(other.getWord()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getProbability() == null ? other.getProbability() == null : this.getProbability().equals(other.getProbability()))
            && (this.getBeginDate() == null ? other.getBeginDate() == null : this.getBeginDate().equals(other.getBeginDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getMerit() == null ? other.getMerit() == null : this.getMerit().equals(other.getMerit()))
            && (this.getGroupFlag() == null ? other.getGroupFlag() == null : this.getGroupFlag().equals(other.getGroupFlag()))
            && (this.getRarity() == null ? other.getRarity() == null : this.getRarity().equals(other.getRarity()))
            && (this.getPrompt() == null ? other.getPrompt() == null : this.getPrompt().equals(other.getPrompt()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWord() == null) ? 0 : getWord().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getProbability() == null) ? 0 : getProbability().hashCode());
        result = prime * result + ((getBeginDate() == null) ? 0 : getBeginDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getMerit() == null) ? 0 : getMerit().hashCode());
        result = prime * result + ((getGroupFlag() == null) ? 0 : getGroupFlag().hashCode());
        result = prime * result + ((getRarity() == null) ? 0 : getRarity().hashCode());
        result = prime * result + ((getPrompt() == null) ? 0 : getPrompt().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_base_word
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", word=").append(word);
        sb.append(", memo=").append(memo);
        sb.append(", probability=").append(probability);
        sb.append(", beginDate=").append(beginDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", merit=").append(merit);
        sb.append(", groupFlag=").append(groupFlag);
        sb.append(", rarity=").append(rarity);
        sb.append(", prompt=").append(prompt);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}