package com.bot.game.dao.entity;

import java.io.Serializable;

public class BotBottleMessage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_bottle_message.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_bottle_message.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_bottle_message.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_bottle_message.send_time
     *
     * @mbggenerated
     */
    private String sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_bottle_message.show_times
     *
     * @mbggenerated
     */
    private Integer showTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_bottle_message.id
     *
     * @return the value of bot_bottle_message.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_bottle_message.id
     *
     * @param id the value for bot_bottle_message.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_bottle_message.content
     *
     * @return the value of bot_bottle_message.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_bottle_message.content
     *
     * @param content the value for bot_bottle_message.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_bottle_message.user_id
     *
     * @return the value of bot_bottle_message.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_bottle_message.user_id
     *
     * @param userId the value for bot_bottle_message.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_bottle_message.send_time
     *
     * @return the value of bot_bottle_message.send_time
     *
     * @mbggenerated
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_bottle_message.send_time
     *
     * @param sendTime the value for bot_bottle_message.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime == null ? null : sendTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_bottle_message.show_times
     *
     * @return the value of bot_bottle_message.show_times
     *
     * @mbggenerated
     */
    public Integer getShowTimes() {
        return showTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_bottle_message.show_times
     *
     * @param showTimes the value for bot_bottle_message.show_times
     *
     * @mbggenerated
     */
    public void setShowTimes(Integer showTimes) {
        this.showTimes = showTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotBottleMessage other = (BotBottleMessage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getSendTime() == null ? other.getSendTime() == null : this.getSendTime().equals(other.getSendTime()))
            && (this.getShowTimes() == null ? other.getShowTimes() == null : this.getShowTimes().equals(other.getShowTimes()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSendTime() == null) ? 0 : getSendTime().hashCode());
        result = prime * result + ((getShowTimes() == null) ? 0 : getShowTimes().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_bottle_message
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", userId=").append(userId);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", showTimes=").append(showTimes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}