package com.bot.game.dao.entity;

import java.io.Serializable;

public class BotDrinkRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_drink_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_drink_record.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_drink_record.drink_time
     *
     * @mbggenerated
     */
    private String drinkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_drink_record.drink_number
     *
     * @mbggenerated
     */
    private Integer drinkNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_drink_record.group_id
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_drink_record.id
     *
     * @return the value of bot_drink_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_drink_record.id
     *
     * @param id the value for bot_drink_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_drink_record.user_id
     *
     * @return the value of bot_drink_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_drink_record.user_id
     *
     * @param userId the value for bot_drink_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_drink_record.drink_time
     *
     * @return the value of bot_drink_record.drink_time
     *
     * @mbggenerated
     */
    public String getDrinkTime() {
        return drinkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_drink_record.drink_time
     *
     * @param drinkTime the value for bot_drink_record.drink_time
     *
     * @mbggenerated
     */
    public void setDrinkTime(String drinkTime) {
        this.drinkTime = drinkTime == null ? null : drinkTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_drink_record.drink_number
     *
     * @return the value of bot_drink_record.drink_number
     *
     * @mbggenerated
     */
    public Integer getDrinkNumber() {
        return drinkNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_drink_record.drink_number
     *
     * @param drinkNumber the value for bot_drink_record.drink_number
     *
     * @mbggenerated
     */
    public void setDrinkNumber(Integer drinkNumber) {
        this.drinkNumber = drinkNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_drink_record.group_id
     *
     * @return the value of bot_drink_record.group_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_drink_record.group_id
     *
     * @param groupId the value for bot_drink_record.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotDrinkRecord other = (BotDrinkRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDrinkTime() == null ? other.getDrinkTime() == null : this.getDrinkTime().equals(other.getDrinkTime()))
            && (this.getDrinkNumber() == null ? other.getDrinkNumber() == null : this.getDrinkNumber().equals(other.getDrinkNumber()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDrinkTime() == null) ? 0 : getDrinkTime().hashCode());
        result = prime * result + ((getDrinkNumber() == null) ? 0 : getDrinkNumber().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_drink_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", drinkTime=").append(drinkTime);
        sb.append(", drinkNumber=").append(drinkNumber);
        sb.append(", groupId=").append(groupId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}