package com.bot.game.dao.entity;

import java.io.Serializable;

public class BotGameUserScore implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_game_user_score.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_game_user_score.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_game_user_score.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_game_user_score.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_game_user_score.current_word
     *
     * @mbggenerated
     */
    private String currentWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_game_user_score.accumulate_merit
     *
     * @mbggenerated
     */
    private Integer accumulateMerit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_game_user_score
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_game_user_score.id
     *
     * @return the value of bot_game_user_score.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_game_user_score.id
     *
     * @param id the value for bot_game_user_score.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_game_user_score.user_id
     *
     * @return the value of bot_game_user_score.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_game_user_score.user_id
     *
     * @param userId the value for bot_game_user_score.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_game_user_score.score
     *
     * @return the value of bot_game_user_score.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_game_user_score.score
     *
     * @param score the value for bot_game_user_score.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_game_user_score.nickname
     *
     * @return the value of bot_game_user_score.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_game_user_score.nickname
     *
     * @param nickname the value for bot_game_user_score.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_game_user_score.current_word
     *
     * @return the value of bot_game_user_score.current_word
     *
     * @mbggenerated
     */
    public String getCurrentWord() {
        return currentWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_game_user_score.current_word
     *
     * @param currentWord the value for bot_game_user_score.current_word
     *
     * @mbggenerated
     */
    public void setCurrentWord(String currentWord) {
        this.currentWord = currentWord == null ? null : currentWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_game_user_score.accumulate_merit
     *
     * @return the value of bot_game_user_score.accumulate_merit
     *
     * @mbggenerated
     */
    public Integer getAccumulateMerit() {
        return accumulateMerit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_game_user_score.accumulate_merit
     *
     * @param accumulateMerit the value for bot_game_user_score.accumulate_merit
     *
     * @mbggenerated
     */
    public void setAccumulateMerit(Integer accumulateMerit) {
        this.accumulateMerit = accumulateMerit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_user_score
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotGameUserScore other = (BotGameUserScore) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getCurrentWord() == null ? other.getCurrentWord() == null : this.getCurrentWord().equals(other.getCurrentWord()))
            && (this.getAccumulateMerit() == null ? other.getAccumulateMerit() == null : this.getAccumulateMerit().equals(other.getAccumulateMerit()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_user_score
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getCurrentWord() == null) ? 0 : getCurrentWord().hashCode());
        result = prime * result + ((getAccumulateMerit() == null) ? 0 : getAccumulateMerit().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_game_user_score
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", score=").append(score);
        sb.append(", nickname=").append(nickname);
        sb.append(", currentWord=").append(currentWord);
        sb.append(", accumulateMerit=").append(accumulateMerit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}