package com.bot.game.dao.entity;

import java.io.Serializable;

public class BotNotice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_notice.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_notice.notice_target_id
     *
     * @mbggenerated
     */
    private String noticeTargetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_notice.notice_content
     *
     * @mbggenerated
     */
    private String noticeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_notice.notice_type
     *
     * @mbggenerated
     */
    private String noticeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_notice.notice_time
     *
     * @mbggenerated
     */
    private String noticeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_notice.at_all_flag
     *
     * @mbggenerated
     */
    private String atAllFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_notice.notice_day
     *
     * @mbggenerated
     */
    private String noticeDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_notice.id
     *
     * @return the value of bot_notice.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_notice.id
     *
     * @param id the value for bot_notice.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_notice.notice_target_id
     *
     * @return the value of bot_notice.notice_target_id
     *
     * @mbggenerated
     */
    public String getNoticeTargetId() {
        return noticeTargetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_notice.notice_target_id
     *
     * @param noticeTargetId the value for bot_notice.notice_target_id
     *
     * @mbggenerated
     */
    public void setNoticeTargetId(String noticeTargetId) {
        this.noticeTargetId = noticeTargetId == null ? null : noticeTargetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_notice.notice_content
     *
     * @return the value of bot_notice.notice_content
     *
     * @mbggenerated
     */
    public String getNoticeContent() {
        return noticeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_notice.notice_content
     *
     * @param noticeContent the value for bot_notice.notice_content
     *
     * @mbggenerated
     */
    public void setNoticeContent(String noticeContent) {
        this.noticeContent = noticeContent == null ? null : noticeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_notice.notice_type
     *
     * @return the value of bot_notice.notice_type
     *
     * @mbggenerated
     */
    public String getNoticeType() {
        return noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_notice.notice_type
     *
     * @param noticeType the value for bot_notice.notice_type
     *
     * @mbggenerated
     */
    public void setNoticeType(String noticeType) {
        this.noticeType = noticeType == null ? null : noticeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_notice.notice_time
     *
     * @return the value of bot_notice.notice_time
     *
     * @mbggenerated
     */
    public String getNoticeTime() {
        return noticeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_notice.notice_time
     *
     * @param noticeTime the value for bot_notice.notice_time
     *
     * @mbggenerated
     */
    public void setNoticeTime(String noticeTime) {
        this.noticeTime = noticeTime == null ? null : noticeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_notice.at_all_flag
     *
     * @return the value of bot_notice.at_all_flag
     *
     * @mbggenerated
     */
    public String getAtAllFlag() {
        return atAllFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_notice.at_all_flag
     *
     * @param atAllFlag the value for bot_notice.at_all_flag
     *
     * @mbggenerated
     */
    public void setAtAllFlag(String atAllFlag) {
        this.atAllFlag = atAllFlag == null ? null : atAllFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_notice.notice_day
     *
     * @return the value of bot_notice.notice_day
     *
     * @mbggenerated
     */
    public String getNoticeDay() {
        return noticeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_notice.notice_day
     *
     * @param noticeDay the value for bot_notice.notice_day
     *
     * @mbggenerated
     */
    public void setNoticeDay(String noticeDay) {
        this.noticeDay = noticeDay == null ? null : noticeDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotNotice other = (BotNotice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNoticeTargetId() == null ? other.getNoticeTargetId() == null : this.getNoticeTargetId().equals(other.getNoticeTargetId()))
            && (this.getNoticeContent() == null ? other.getNoticeContent() == null : this.getNoticeContent().equals(other.getNoticeContent()))
            && (this.getNoticeType() == null ? other.getNoticeType() == null : this.getNoticeType().equals(other.getNoticeType()))
            && (this.getNoticeTime() == null ? other.getNoticeTime() == null : this.getNoticeTime().equals(other.getNoticeTime()))
            && (this.getAtAllFlag() == null ? other.getAtAllFlag() == null : this.getAtAllFlag().equals(other.getAtAllFlag()))
            && (this.getNoticeDay() == null ? other.getNoticeDay() == null : this.getNoticeDay().equals(other.getNoticeDay()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNoticeTargetId() == null) ? 0 : getNoticeTargetId().hashCode());
        result = prime * result + ((getNoticeContent() == null) ? 0 : getNoticeContent().hashCode());
        result = prime * result + ((getNoticeType() == null) ? 0 : getNoticeType().hashCode());
        result = prime * result + ((getNoticeTime() == null) ? 0 : getNoticeTime().hashCode());
        result = prime * result + ((getAtAllFlag() == null) ? 0 : getAtAllFlag().hashCode());
        result = prime * result + ((getNoticeDay() == null) ? 0 : getNoticeDay().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_notice
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", noticeTargetId=").append(noticeTargetId);
        sb.append(", noticeContent=").append(noticeContent);
        sb.append(", noticeType=").append(noticeType);
        sb.append(", noticeTime=").append(noticeTime);
        sb.append(", atAllFlag=").append(atAllFlag);
        sb.append(", noticeDay=").append(noticeDay);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}