package com.bot.game.dao.entity;

import java.io.Serializable;

public class BotRedPacket implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_red_packet.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_red_packet.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_red_packet.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_red_packet.active_code
     *
     * @mbggenerated
     */
    private String activeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_red_packet.fetch_user_id
     *
     * @mbggenerated
     */
    private String fetchUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_red_packet.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_red_packet.id
     *
     * @return the value of bot_red_packet.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_red_packet.id
     *
     * @param id the value for bot_red_packet.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_red_packet.content
     *
     * @return the value of bot_red_packet.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_red_packet.content
     *
     * @param content the value for bot_red_packet.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_red_packet.status
     *
     * @return the value of bot_red_packet.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_red_packet.status
     *
     * @param status the value for bot_red_packet.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_red_packet.active_code
     *
     * @return the value of bot_red_packet.active_code
     *
     * @mbggenerated
     */
    public String getActiveCode() {
        return activeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_red_packet.active_code
     *
     * @param activeCode the value for bot_red_packet.active_code
     *
     * @mbggenerated
     */
    public void setActiveCode(String activeCode) {
        this.activeCode = activeCode == null ? null : activeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_red_packet.fetch_user_id
     *
     * @return the value of bot_red_packet.fetch_user_id
     *
     * @mbggenerated
     */
    public String getFetchUserId() {
        return fetchUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_red_packet.fetch_user_id
     *
     * @param fetchUserId the value for bot_red_packet.fetch_user_id
     *
     * @mbggenerated
     */
    public void setFetchUserId(String fetchUserId) {
        this.fetchUserId = fetchUserId == null ? null : fetchUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_red_packet.version
     *
     * @return the value of bot_red_packet.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_red_packet.version
     *
     * @param version the value for bot_red_packet.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotRedPacket other = (BotRedPacket) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getActiveCode() == null ? other.getActiveCode() == null : this.getActiveCode().equals(other.getActiveCode()))
            && (this.getFetchUserId() == null ? other.getFetchUserId() == null : this.getFetchUserId().equals(other.getFetchUserId()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getActiveCode() == null) ? 0 : getActiveCode().hashCode());
        result = prime * result + ((getFetchUserId() == null) ? 0 : getFetchUserId().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_red_packet
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", status=").append(status);
        sb.append(", activeCode=").append(activeCode);
        sb.append(", fetchUserId=").append(fetchUserId);
        sb.append(", version=").append(version);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}