package com.bot.game.dao.entity;

import java.io.Serializable;

public class BotUserConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.chat_engine
     *
     * @mbggenerated
     */
    private String chatEngine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.morning_type
     *
     * @mbggenerated
     */
    private String morningType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.work_daily_config
     *
     * @mbggenerated
     */
    private String workDailyConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.jx_server
     *
     * @mbggenerated
     */
    private String jxServer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.drink_switch
     *
     * @mbggenerated
     */
    private String drinkSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.drink_chat_id
     *
     * @mbggenerated
     */
    private String drinkChatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.invite_code
     *
     * @mbggenerated
     */
    private String inviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.english_switch
     *
     * @mbggenerated
     */
    private String englishSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.jx_open_server
     *
     * @mbggenerated
     */
    private String jxOpenServer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.jx_server_status
     *
     * @mbggenerated
     */
    private String jxServerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.chat_frequency
     *
     * @mbggenerated
     */
    private String chatFrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.emoji_switch
     *
     * @mbggenerated
     */
    private String emojiSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.bottle_auto_switch
     *
     * @mbggenerated
     */
    private String bottleAutoSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_config.welcome_content
     *
     * @mbggenerated
     */
    private String welcomeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.id
     *
     * @return the value of bot_user_config.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.id
     *
     * @param id the value for bot_user_config.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.user_id
     *
     * @return the value of bot_user_config.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.user_id
     *
     * @param userId the value for bot_user_config.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.chat_engine
     *
     * @return the value of bot_user_config.chat_engine
     *
     * @mbggenerated
     */
    public String getChatEngine() {
        return chatEngine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.chat_engine
     *
     * @param chatEngine the value for bot_user_config.chat_engine
     *
     * @mbggenerated
     */
    public void setChatEngine(String chatEngine) {
        this.chatEngine = chatEngine == null ? null : chatEngine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.morning_type
     *
     * @return the value of bot_user_config.morning_type
     *
     * @mbggenerated
     */
    public String getMorningType() {
        return morningType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.morning_type
     *
     * @param morningType the value for bot_user_config.morning_type
     *
     * @mbggenerated
     */
    public void setMorningType(String morningType) {
        this.morningType = morningType == null ? null : morningType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.work_daily_config
     *
     * @return the value of bot_user_config.work_daily_config
     *
     * @mbggenerated
     */
    public String getWorkDailyConfig() {
        return workDailyConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.work_daily_config
     *
     * @param workDailyConfig the value for bot_user_config.work_daily_config
     *
     * @mbggenerated
     */
    public void setWorkDailyConfig(String workDailyConfig) {
        this.workDailyConfig = workDailyConfig == null ? null : workDailyConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.jx_server
     *
     * @return the value of bot_user_config.jx_server
     *
     * @mbggenerated
     */
    public String getJxServer() {
        return jxServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.jx_server
     *
     * @param jxServer the value for bot_user_config.jx_server
     *
     * @mbggenerated
     */
    public void setJxServer(String jxServer) {
        this.jxServer = jxServer == null ? null : jxServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.drink_switch
     *
     * @return the value of bot_user_config.drink_switch
     *
     * @mbggenerated
     */
    public String getDrinkSwitch() {
        return drinkSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.drink_switch
     *
     * @param drinkSwitch the value for bot_user_config.drink_switch
     *
     * @mbggenerated
     */
    public void setDrinkSwitch(String drinkSwitch) {
        this.drinkSwitch = drinkSwitch == null ? null : drinkSwitch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.drink_chat_id
     *
     * @return the value of bot_user_config.drink_chat_id
     *
     * @mbggenerated
     */
    public String getDrinkChatId() {
        return drinkChatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.drink_chat_id
     *
     * @param drinkChatId the value for bot_user_config.drink_chat_id
     *
     * @mbggenerated
     */
    public void setDrinkChatId(String drinkChatId) {
        this.drinkChatId = drinkChatId == null ? null : drinkChatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.invite_code
     *
     * @return the value of bot_user_config.invite_code
     *
     * @mbggenerated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.invite_code
     *
     * @param inviteCode the value for bot_user_config.invite_code
     *
     * @mbggenerated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.english_switch
     *
     * @return the value of bot_user_config.english_switch
     *
     * @mbggenerated
     */
    public String getEnglishSwitch() {
        return englishSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.english_switch
     *
     * @param englishSwitch the value for bot_user_config.english_switch
     *
     * @mbggenerated
     */
    public void setEnglishSwitch(String englishSwitch) {
        this.englishSwitch = englishSwitch == null ? null : englishSwitch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.jx_open_server
     *
     * @return the value of bot_user_config.jx_open_server
     *
     * @mbggenerated
     */
    public String getJxOpenServer() {
        return jxOpenServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.jx_open_server
     *
     * @param jxOpenServer the value for bot_user_config.jx_open_server
     *
     * @mbggenerated
     */
    public void setJxOpenServer(String jxOpenServer) {
        this.jxOpenServer = jxOpenServer == null ? null : jxOpenServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.jx_server_status
     *
     * @return the value of bot_user_config.jx_server_status
     *
     * @mbggenerated
     */
    public String getJxServerStatus() {
        return jxServerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.jx_server_status
     *
     * @param jxServerStatus the value for bot_user_config.jx_server_status
     *
     * @mbggenerated
     */
    public void setJxServerStatus(String jxServerStatus) {
        this.jxServerStatus = jxServerStatus == null ? null : jxServerStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.chat_frequency
     *
     * @return the value of bot_user_config.chat_frequency
     *
     * @mbggenerated
     */
    public String getChatFrequency() {
        return chatFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.chat_frequency
     *
     * @param chatFrequency the value for bot_user_config.chat_frequency
     *
     * @mbggenerated
     */
    public void setChatFrequency(String chatFrequency) {
        this.chatFrequency = chatFrequency == null ? null : chatFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.emoji_switch
     *
     * @return the value of bot_user_config.emoji_switch
     *
     * @mbggenerated
     */
    public String getEmojiSwitch() {
        return emojiSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.emoji_switch
     *
     * @param emojiSwitch the value for bot_user_config.emoji_switch
     *
     * @mbggenerated
     */
    public void setEmojiSwitch(String emojiSwitch) {
        this.emojiSwitch = emojiSwitch == null ? null : emojiSwitch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.bottle_auto_switch
     *
     * @return the value of bot_user_config.bottle_auto_switch
     *
     * @mbggenerated
     */
    public String getBottleAutoSwitch() {
        return bottleAutoSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.bottle_auto_switch
     *
     * @param bottleAutoSwitch the value for bot_user_config.bottle_auto_switch
     *
     * @mbggenerated
     */
    public void setBottleAutoSwitch(String bottleAutoSwitch) {
        this.bottleAutoSwitch = bottleAutoSwitch == null ? null : bottleAutoSwitch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_config.welcome_content
     *
     * @return the value of bot_user_config.welcome_content
     *
     * @mbggenerated
     */
    public String getWelcomeContent() {
        return welcomeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_config.welcome_content
     *
     * @param welcomeContent the value for bot_user_config.welcome_content
     *
     * @mbggenerated
     */
    public void setWelcomeContent(String welcomeContent) {
        this.welcomeContent = welcomeContent == null ? null : welcomeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotUserConfig other = (BotUserConfig) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getChatEngine() == null ? other.getChatEngine() == null : this.getChatEngine().equals(other.getChatEngine()))
            && (this.getMorningType() == null ? other.getMorningType() == null : this.getMorningType().equals(other.getMorningType()))
            && (this.getWorkDailyConfig() == null ? other.getWorkDailyConfig() == null : this.getWorkDailyConfig().equals(other.getWorkDailyConfig()))
            && (this.getJxServer() == null ? other.getJxServer() == null : this.getJxServer().equals(other.getJxServer()))
            && (this.getDrinkSwitch() == null ? other.getDrinkSwitch() == null : this.getDrinkSwitch().equals(other.getDrinkSwitch()))
            && (this.getDrinkChatId() == null ? other.getDrinkChatId() == null : this.getDrinkChatId().equals(other.getDrinkChatId()))
            && (this.getInviteCode() == null ? other.getInviteCode() == null : this.getInviteCode().equals(other.getInviteCode()))
            && (this.getEnglishSwitch() == null ? other.getEnglishSwitch() == null : this.getEnglishSwitch().equals(other.getEnglishSwitch()))
            && (this.getJxOpenServer() == null ? other.getJxOpenServer() == null : this.getJxOpenServer().equals(other.getJxOpenServer()))
            && (this.getJxServerStatus() == null ? other.getJxServerStatus() == null : this.getJxServerStatus().equals(other.getJxServerStatus()))
            && (this.getChatFrequency() == null ? other.getChatFrequency() == null : this.getChatFrequency().equals(other.getChatFrequency()))
            && (this.getEmojiSwitch() == null ? other.getEmojiSwitch() == null : this.getEmojiSwitch().equals(other.getEmojiSwitch()))
            && (this.getBottleAutoSwitch() == null ? other.getBottleAutoSwitch() == null : this.getBottleAutoSwitch().equals(other.getBottleAutoSwitch()))
            && (this.getWelcomeContent() == null ? other.getWelcomeContent() == null : this.getWelcomeContent().equals(other.getWelcomeContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getChatEngine() == null) ? 0 : getChatEngine().hashCode());
        result = prime * result + ((getMorningType() == null) ? 0 : getMorningType().hashCode());
        result = prime * result + ((getWorkDailyConfig() == null) ? 0 : getWorkDailyConfig().hashCode());
        result = prime * result + ((getJxServer() == null) ? 0 : getJxServer().hashCode());
        result = prime * result + ((getDrinkSwitch() == null) ? 0 : getDrinkSwitch().hashCode());
        result = prime * result + ((getDrinkChatId() == null) ? 0 : getDrinkChatId().hashCode());
        result = prime * result + ((getInviteCode() == null) ? 0 : getInviteCode().hashCode());
        result = prime * result + ((getEnglishSwitch() == null) ? 0 : getEnglishSwitch().hashCode());
        result = prime * result + ((getJxOpenServer() == null) ? 0 : getJxOpenServer().hashCode());
        result = prime * result + ((getJxServerStatus() == null) ? 0 : getJxServerStatus().hashCode());
        result = prime * result + ((getChatFrequency() == null) ? 0 : getChatFrequency().hashCode());
        result = prime * result + ((getEmojiSwitch() == null) ? 0 : getEmojiSwitch().hashCode());
        result = prime * result + ((getBottleAutoSwitch() == null) ? 0 : getBottleAutoSwitch().hashCode());
        result = prime * result + ((getWelcomeContent() == null) ? 0 : getWelcomeContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", chatEngine=").append(chatEngine);
        sb.append(", morningType=").append(morningType);
        sb.append(", workDailyConfig=").append(workDailyConfig);
        sb.append(", jxServer=").append(jxServer);
        sb.append(", drinkSwitch=").append(drinkSwitch);
        sb.append(", drinkChatId=").append(drinkChatId);
        sb.append(", inviteCode=").append(inviteCode);
        sb.append(", englishSwitch=").append(englishSwitch);
        sb.append(", jxOpenServer=").append(jxOpenServer);
        sb.append(", jxServerStatus=").append(jxServerStatus);
        sb.append(", chatFrequency=").append(chatFrequency);
        sb.append(", emojiSwitch=").append(emojiSwitch);
        sb.append(", bottleAutoSwitch=").append(bottleAutoSwitch);
        sb.append(", welcomeContent=").append(welcomeContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}