package com.bot.game.dao.entity;

import java.util.ArrayList;
import java.util.List;

public class BotUserConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public BotUserConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andChatEngineIsNull() {
            addCriterion("chat_engine is null");
            return (Criteria) this;
        }

        public Criteria andChatEngineIsNotNull() {
            addCriterion("chat_engine is not null");
            return (Criteria) this;
        }

        public Criteria andChatEngineEqualTo(String value) {
            addCriterion("chat_engine =", value, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineNotEqualTo(String value) {
            addCriterion("chat_engine <>", value, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineGreaterThan(String value) {
            addCriterion("chat_engine >", value, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineGreaterThanOrEqualTo(String value) {
            addCriterion("chat_engine >=", value, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineLessThan(String value) {
            addCriterion("chat_engine <", value, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineLessThanOrEqualTo(String value) {
            addCriterion("chat_engine <=", value, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineLike(String value) {
            addCriterion("chat_engine like", value, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineNotLike(String value) {
            addCriterion("chat_engine not like", value, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineIn(List<String> values) {
            addCriterion("chat_engine in", values, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineNotIn(List<String> values) {
            addCriterion("chat_engine not in", values, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineBetween(String value1, String value2) {
            addCriterion("chat_engine between", value1, value2, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andChatEngineNotBetween(String value1, String value2) {
            addCriterion("chat_engine not between", value1, value2, "chatEngine");
            return (Criteria) this;
        }

        public Criteria andMorningTypeIsNull() {
            addCriterion("morning_type is null");
            return (Criteria) this;
        }

        public Criteria andMorningTypeIsNotNull() {
            addCriterion("morning_type is not null");
            return (Criteria) this;
        }

        public Criteria andMorningTypeEqualTo(String value) {
            addCriterion("morning_type =", value, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeNotEqualTo(String value) {
            addCriterion("morning_type <>", value, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeGreaterThan(String value) {
            addCriterion("morning_type >", value, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeGreaterThanOrEqualTo(String value) {
            addCriterion("morning_type >=", value, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeLessThan(String value) {
            addCriterion("morning_type <", value, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeLessThanOrEqualTo(String value) {
            addCriterion("morning_type <=", value, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeLike(String value) {
            addCriterion("morning_type like", value, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeNotLike(String value) {
            addCriterion("morning_type not like", value, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeIn(List<String> values) {
            addCriterion("morning_type in", values, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeNotIn(List<String> values) {
            addCriterion("morning_type not in", values, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeBetween(String value1, String value2) {
            addCriterion("morning_type between", value1, value2, "morningType");
            return (Criteria) this;
        }

        public Criteria andMorningTypeNotBetween(String value1, String value2) {
            addCriterion("morning_type not between", value1, value2, "morningType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot_user_config
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot_user_config
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}