package com.bot.game.dao.entity;

import java.io.Serializable;

public class BotUserBlindBox implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_blind_box.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_blind_box.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_blind_box.box_content
     *
     * @mbggenerated
     */
    private String boxContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_blind_box.fetch_date
     *
     * @mbggenerated
     */
    private String fetchDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_blind_box.id
     *
     * @return the value of bot_user_blind_box.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_blind_box.id
     *
     * @param id the value for bot_user_blind_box.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_blind_box.user_id
     *
     * @return the value of bot_user_blind_box.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_blind_box.user_id
     *
     * @param userId the value for bot_user_blind_box.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_blind_box.box_content
     *
     * @return the value of bot_user_blind_box.box_content
     *
     * @mbggenerated
     */
    public String getBoxContent() {
        return boxContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_blind_box.box_content
     *
     * @param boxContent the value for bot_user_blind_box.box_content
     *
     * @mbggenerated
     */
    public void setBoxContent(String boxContent) {
        this.boxContent = boxContent == null ? null : boxContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_blind_box.fetch_date
     *
     * @return the value of bot_user_blind_box.fetch_date
     *
     * @mbggenerated
     */
    public String getFetchDate() {
        return fetchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_blind_box.fetch_date
     *
     * @param fetchDate the value for bot_user_blind_box.fetch_date
     *
     * @mbggenerated
     */
    public void setFetchDate(String fetchDate) {
        this.fetchDate = fetchDate == null ? null : fetchDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotUserBlindBox other = (BotUserBlindBox) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getBoxContent() == null ? other.getBoxContent() == null : this.getBoxContent().equals(other.getBoxContent()))
            && (this.getFetchDate() == null ? other.getFetchDate() == null : this.getFetchDate().equals(other.getFetchDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getBoxContent() == null) ? 0 : getBoxContent().hashCode());
        result = prime * result + ((getFetchDate() == null) ? 0 : getFetchDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_blind_box
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", boxContent=").append(boxContent);
        sb.append(", fetchDate=").append(fetchDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}