package com.bot.game.dao.entity;

import java.io.Serializable;

public class BotUserWord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_word.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_word.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_word.word_id
     *
     * @mbggenerated
     */
    private Long wordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_word.word_content
     *
     * @mbggenerated
     */
    private String wordContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_word.fetch_date
     *
     * @mbggenerated
     */
    private String fetchDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_word.rarity
     *
     * @mbggenerated
     */
    private String rarity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_word.merit
     *
     * @mbggenerated
     */
    private Integer merit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_word.id
     *
     * @return the value of bot_user_word.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_word.id
     *
     * @param id the value for bot_user_word.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_word.user_id
     *
     * @return the value of bot_user_word.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_word.user_id
     *
     * @param userId the value for bot_user_word.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_word.word_id
     *
     * @return the value of bot_user_word.word_id
     *
     * @mbggenerated
     */
    public Long getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_word.word_id
     *
     * @param wordId the value for bot_user_word.word_id
     *
     * @mbggenerated
     */
    public void setWordId(Long wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_word.word_content
     *
     * @return the value of bot_user_word.word_content
     *
     * @mbggenerated
     */
    public String getWordContent() {
        return wordContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_word.word_content
     *
     * @param wordContent the value for bot_user_word.word_content
     *
     * @mbggenerated
     */
    public void setWordContent(String wordContent) {
        this.wordContent = wordContent == null ? null : wordContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_word.fetch_date
     *
     * @return the value of bot_user_word.fetch_date
     *
     * @mbggenerated
     */
    public String getFetchDate() {
        return fetchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_word.fetch_date
     *
     * @param fetchDate the value for bot_user_word.fetch_date
     *
     * @mbggenerated
     */
    public void setFetchDate(String fetchDate) {
        this.fetchDate = fetchDate == null ? null : fetchDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_word.rarity
     *
     * @return the value of bot_user_word.rarity
     *
     * @mbggenerated
     */
    public String getRarity() {
        return rarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_word.rarity
     *
     * @param rarity the value for bot_user_word.rarity
     *
     * @mbggenerated
     */
    public void setRarity(String rarity) {
        this.rarity = rarity == null ? null : rarity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_word.merit
     *
     * @return the value of bot_user_word.merit
     *
     * @mbggenerated
     */
    public Integer getMerit() {
        return merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_word.merit
     *
     * @param merit the value for bot_user_word.merit
     *
     * @mbggenerated
     */
    public void setMerit(Integer merit) {
        this.merit = merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotUserWord other = (BotUserWord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getWordId() == null ? other.getWordId() == null : this.getWordId().equals(other.getWordId()))
            && (this.getWordContent() == null ? other.getWordContent() == null : this.getWordContent().equals(other.getWordContent()))
            && (this.getFetchDate() == null ? other.getFetchDate() == null : this.getFetchDate().equals(other.getFetchDate()))
            && (this.getRarity() == null ? other.getRarity() == null : this.getRarity().equals(other.getRarity()))
            && (this.getMerit() == null ? other.getMerit() == null : this.getMerit().equals(other.getMerit()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getWordId() == null) ? 0 : getWordId().hashCode());
        result = prime * result + ((getWordContent() == null) ? 0 : getWordContent().hashCode());
        result = prime * result + ((getFetchDate() == null) ? 0 : getFetchDate().hashCode());
        result = prime * result + ((getRarity() == null) ? 0 : getRarity().hashCode());
        result = prime * result + ((getMerit() == null) ? 0 : getMerit().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_word
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", wordId=").append(wordId);
        sb.append(", wordContent=").append(wordContent);
        sb.append(", fetchDate=").append(fetchDate);
        sb.append(", rarity=").append(rarity);
        sb.append(", merit=").append(merit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}