package com.bot.game.dao.entity;

import java.util.ArrayList;
import java.util.List;

public class JXCacheExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public JXCacheExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCacheTypeIsNull() {
            addCriterion("cache_type is null");
            return (Criteria) this;
        }

        public Criteria andCacheTypeIsNotNull() {
            addCriterion("cache_type is not null");
            return (Criteria) this;
        }

        public Criteria andCacheTypeEqualTo(String value) {
            addCriterion("cache_type =", value, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeNotEqualTo(String value) {
            addCriterion("cache_type <>", value, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeGreaterThan(String value) {
            addCriterion("cache_type >", value, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeGreaterThanOrEqualTo(String value) {
            addCriterion("cache_type >=", value, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeLessThan(String value) {
            addCriterion("cache_type <", value, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeLessThanOrEqualTo(String value) {
            addCriterion("cache_type <=", value, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeLike(String value) {
            addCriterion("cache_type like", value, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeNotLike(String value) {
            addCriterion("cache_type not like", value, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeIn(List<String> values) {
            addCriterion("cache_type in", values, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeNotIn(List<String> values) {
            addCriterion("cache_type not in", values, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeBetween(String value1, String value2) {
            addCriterion("cache_type between", value1, value2, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheTypeNotBetween(String value1, String value2) {
            addCriterion("cache_type not between", value1, value2, "cacheType");
            return (Criteria) this;
        }

        public Criteria andCacheKeyIsNull() {
            addCriterion("cache_key is null");
            return (Criteria) this;
        }

        public Criteria andCacheKeyIsNotNull() {
            addCriterion("cache_key is not null");
            return (Criteria) this;
        }

        public Criteria andCacheKeyEqualTo(String value) {
            addCriterion("cache_key =", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyNotEqualTo(String value) {
            addCriterion("cache_key <>", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyGreaterThan(String value) {
            addCriterion("cache_key >", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyGreaterThanOrEqualTo(String value) {
            addCriterion("cache_key >=", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyLessThan(String value) {
            addCriterion("cache_key <", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyLessThanOrEqualTo(String value) {
            addCriterion("cache_key <=", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyLike(String value) {
            addCriterion("cache_key like", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyNotLike(String value) {
            addCriterion("cache_key not like", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyIn(List<String> values) {
            addCriterion("cache_key in", values, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyNotIn(List<String> values) {
            addCriterion("cache_key not in", values, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyBetween(String value1, String value2) {
            addCriterion("cache_key between", value1, value2, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyNotBetween(String value1, String value2) {
            addCriterion("cache_key not between", value1, value2, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andSaveDateIsNull() {
            addCriterion("save_date is null");
            return (Criteria) this;
        }

        public Criteria andSaveDateIsNotNull() {
            addCriterion("save_date is not null");
            return (Criteria) this;
        }

        public Criteria andSaveDateEqualTo(String value) {
            addCriterion("save_date =", value, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateNotEqualTo(String value) {
            addCriterion("save_date <>", value, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateGreaterThan(String value) {
            addCriterion("save_date >", value, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateGreaterThanOrEqualTo(String value) {
            addCriterion("save_date >=", value, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateLessThan(String value) {
            addCriterion("save_date <", value, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateLessThanOrEqualTo(String value) {
            addCriterion("save_date <=", value, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateLike(String value) {
            addCriterion("save_date like", value, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateNotLike(String value) {
            addCriterion("save_date not like", value, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateIn(List<String> values) {
            addCriterion("save_date in", values, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateNotIn(List<String> values) {
            addCriterion("save_date not in", values, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateBetween(String value1, String value2) {
            addCriterion("save_date between", value1, value2, "saveDate");
            return (Criteria) this;
        }

        public Criteria andSaveDateNotBetween(String value1, String value2) {
            addCriterion("save_date not between", value1, value2, "saveDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot_jx_cache
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot_jx_cache
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}