package com.bot.game.dao.entity;

import java.io.Serializable;

public class JXShowHistoryQuery implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_jx_show_history_query.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_jx_show_history_query.query_id
     *
     * @mbggenerated
     */
    private String queryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_jx_show_history_query.show_url
     *
     * @mbggenerated
     */
    private String showUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_jx_show_history_query.query_date
     *
     * @mbggenerated
     */
    private String queryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_jx_show_history_query.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_jx_show_history_query.id
     *
     * @return the value of bot_jx_show_history_query.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_jx_show_history_query.id
     *
     * @param id the value for bot_jx_show_history_query.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_jx_show_history_query.query_id
     *
     * @return the value of bot_jx_show_history_query.query_id
     *
     * @mbggenerated
     */
    public String getQueryId() {
        return queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_jx_show_history_query.query_id
     *
     * @param queryId the value for bot_jx_show_history_query.query_id
     *
     * @mbggenerated
     */
    public void setQueryId(String queryId) {
        this.queryId = queryId == null ? null : queryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_jx_show_history_query.show_url
     *
     * @return the value of bot_jx_show_history_query.show_url
     *
     * @mbggenerated
     */
    public String getShowUrl() {
        return showUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_jx_show_history_query.show_url
     *
     * @param showUrl the value for bot_jx_show_history_query.show_url
     *
     * @mbggenerated
     */
    public void setShowUrl(String showUrl) {
        this.showUrl = showUrl == null ? null : showUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_jx_show_history_query.query_date
     *
     * @return the value of bot_jx_show_history_query.query_date
     *
     * @mbggenerated
     */
    public String getQueryDate() {
        return queryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_jx_show_history_query.query_date
     *
     * @param queryDate the value for bot_jx_show_history_query.query_date
     *
     * @mbggenerated
     */
    public void setQueryDate(String queryDate) {
        this.queryDate = queryDate == null ? null : queryDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_jx_show_history_query.title
     *
     * @return the value of bot_jx_show_history_query.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_jx_show_history_query.title
     *
     * @param title the value for bot_jx_show_history_query.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JXShowHistoryQuery other = (JXShowHistoryQuery) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getQueryId() == null ? other.getQueryId() == null : this.getQueryId().equals(other.getQueryId()))
            && (this.getShowUrl() == null ? other.getShowUrl() == null : this.getShowUrl().equals(other.getShowUrl()))
            && (this.getQueryDate() == null ? other.getQueryDate() == null : this.getQueryDate().equals(other.getQueryDate()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getQueryId() == null) ? 0 : getQueryId().hashCode());
        result = prime * result + ((getShowUrl() == null) ? 0 : getShowUrl().hashCode());
        result = prime * result + ((getQueryDate() == null) ? 0 : getQueryDate().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_jx_show_history_query
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", queryId=").append(queryId);
        sb.append(", showUrl=").append(showUrl);
        sb.append(", queryDate=").append(queryDate);
        sb.append(", title=").append(title);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}