package com.bot.game.dao.entity;

import java.io.Serializable;

public class UserBind implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_bind.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_bind.wx_user_token
     *
     * @mbggenerated
     */
    private String wxUserToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_user_bind.qq_user_token
     *
     * @mbggenerated
     */
    private String qqUserToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_bind.id
     *
     * @return the value of bot_user_bind.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_bind.id
     *
     * @param id the value for bot_user_bind.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_bind.wx_user_token
     *
     * @return the value of bot_user_bind.wx_user_token
     *
     * @mbggenerated
     */
    public String getWxUserToken() {
        return wxUserToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_bind.wx_user_token
     *
     * @param wxUserToken the value for bot_user_bind.wx_user_token
     *
     * @mbggenerated
     */
    public void setWxUserToken(String wxUserToken) {
        this.wxUserToken = wxUserToken == null ? null : wxUserToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_user_bind.qq_user_token
     *
     * @return the value of bot_user_bind.qq_user_token
     *
     * @mbggenerated
     */
    public String getQqUserToken() {
        return qqUserToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_user_bind.qq_user_token
     *
     * @param qqUserToken the value for bot_user_bind.qq_user_token
     *
     * @mbggenerated
     */
    public void setQqUserToken(String qqUserToken) {
        this.qqUserToken = qqUserToken == null ? null : qqUserToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserBind other = (UserBind) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWxUserToken() == null ? other.getWxUserToken() == null : this.getWxUserToken().equals(other.getWxUserToken()))
            && (this.getQqUserToken() == null ? other.getQqUserToken() == null : this.getQqUserToken().equals(other.getQqUserToken()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWxUserToken() == null) ? 0 : getWxUserToken().hashCode());
        result = prime * result + ((getQqUserToken() == null) ? 0 : getQqUserToken().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_user_bind
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", wxUserToken=").append(wxUserToken);
        sb.append(", qqUserToken=").append(qqUserToken);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}